// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkx560vJwzoq9aHMC41JJZqVwEmNTe6BQ',
    appId: '1:968908516551:web:dd3b9344a5dbdf77f562e2',
    messagingSenderId: '968908516551',
    projectId: 'whiskr-7a530',
    authDomain: 'whiskr-7a530.firebaseapp.com',
    storageBucket: 'whiskr-7a530.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp8kHLC8tI0qZN_lZqm3XkWmcops7ZM7Y',
    appId: '1:968908516551:android:45b64cdbfde86008f562e2',
    messagingSenderId: '968908516551',
    projectId: 'whiskr-7a530',
    storageBucket: 'whiskr-7a530.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkuBLgEM9S94_u-yj7MU4ep8nl0Yayfqk',
    appId: '1:968908516551:ios:fac3cd5d84216133f562e2',
    messagingSenderId: '968908516551',
    projectId: 'whiskr-7a530',
    storageBucket: 'whiskr-7a530.appspot.com',
    iosBundleId: 'com.example.whiskr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkuBLgEM9S94_u-yj7MU4ep8nl0Yayfqk',
    appId: '1:968908516551:ios:fac3cd5d84216133f562e2',
    messagingSenderId: '968908516551',
    projectId: 'whiskr-7a530',
    storageBucket: 'whiskr-7a530.appspot.com',
    iosBundleId: 'com.example.whiskr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkx560vJwzoq9aHMC41JJZqVwEmNTe6BQ',
    appId: '1:968908516551:web:4b340512ee2d3965f562e2',
    messagingSenderId: '968908516551',
    projectId: 'whiskr-7a530',
    authDomain: 'whiskr-7a530.firebaseapp.com',
    storageBucket: 'whiskr-7a530.appspot.com',
  );
}
